### PR TITLE
HFX-1717: Backport of the TLS 1.2 support to XS 6.1

### PR DESCRIPTION
**Pull request by fillzero**
Backport of the TLS 1.2 support to XS 6.1

### CODE REVIEW

**Comment by fillzero** [comment]
Hi @thomassa ,
Below two commits are not simply changes and revert changes, 
the changed lines of code is different:

```
Revert "CP-16361: Backout stunnel_xs from HFP Drown"  
```

**+834 −310** 

```
CP-16361: Backout stunnel_xs from HFP Drown 
```

 **+11 −855** 

So, it is not easily to omit these two commits.

**Comment by thomassa** [comment]
I see. Several of the changes in
commit 9c4021e `CP-16361: Backout stunnel_xs from HFP Drown`
are not undone in
commit 7161615 `Revert "CP-16361: Backout stunnel_xs from HFP Drown"`

This doesn't seem right... have these changes had a thorough review in pull-requests for some other LCM branch, or is this pull-request the first time these changes are being reviewed?

**Comment by thomassa** [comment]
Are those changes from 9c4021e `CP-16361: Backout stunnel_xs from HFP Drown` all undone in the rest of the pull request though? It looks as if its changes to `message-switch.spec` get undone correctly, at least.

**Comment by fillzero** [comment]
Hi @thomassa , the revert commit https://github.com/xenserver/xen-api-backports/pull/26/commits/71616154e7d08952e2980b5faaf66d7f7af60f1a is a set of revert commits.

This revert commits is generated by below commands:

```
git revert --no-commit 9c4021e34ddb0a67a2bd38327e197cc5e8445da1 # revert 1st commit without commit
git revert --no-commit 0f04ccf6fc1db2c78d445b6733fcc787b3a7383a # revert 2nd commit without commit
git revert  b7666417dd348878ab31198b968e0b485534e6b5 # revert 3rd commit and commit
```

So, I removed three change commits, and one revert change commit.
It is much more clear now. Thank you.

**Pull request merged**
