### PR TITLE
Backport the missed spec updates to clearwater-sp1-bugfix for HFX-1716.

### PR DESCRIPTION
**Pull request by huizh**
Signed-off-by: Hui Zhang hui.zhang@citrix.com

### CODE REVIEW

**Comment by huizh** [comment]
Hi @thomassa, some updates were missed to port to clearwater-sp1-bugfix before. 
Could you please help merge this commit?

Thank you.

**Comment by thomassa** [comment]
`vhd-tool.spec` is lacking a changelog entry and release-increment.
I'm merging this now anyway to fix the broken build, but can we fix up those things afterwards in another pull-request?

**Comment by huizh** [comment]
Thank you @thomassa 
For vhd-tool.spec, I think the changelog is already there
https://github.com/xenserver/xen-api-backports/pull/27/files#diff-e0fafd72afcc594c72aed82c86bc0b85R61
right?

**Comment by thomassa** [comment]
The file's changelog has a pre-existing changelog entry

```
* Mon Dec 14 2015 Si Beaumont <simon.beaumont@citrix.com> - 0.7.4-2
- Recompile against openssl-xs
```

but it in fact it was using `openssl` (not `openssl-xs`) until just now.
So I think it needs a new changelog entry like "Really use openssl-xs instead of openssl now."
(And increment the release from 3 to 4.)

**Comment by huizh** [comment]
OK I see. Thanks. Will update and send a new PR.

**Pull request merged**
