### PR TITLE
CA-202375: Add stunnel to api-backports

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Phus Lu phus.lu@citrix.com
(cherry picked from commit 1e297214af76f930cf227cc8555e2a6cbe8c0cbf)
Signed-off-by: Phus Lu phus.lu@citrix.com
(cherry picked from commit fd2be659056724dd5663b75e1db3da5a49279189)

Signed-off-by: Phus Lu phus.lu@citrix.com

### CODE REVIEW

**Comment by ghost** [comment]
Related with https://github.com/xenserver/planex/pull/263

**Comment by thomassa** [comment]
@xen-git retest this please

**Comment by thomassa** [comment]
Now that I have merged xenserver/planex#263 I have asked xen-git to retest this pullreq.
If that passes we can merge this.

**Comment by ghost** [comment]
sanibel-bugfix(https://xenbuilder/builds?q_view=summary&q_product=carbon&q_branch=sanibel-bugfix) looks good.

**Comment by thomassa** [comment]
Yes, the latest build of the sanibel-bugfix branch looks good, but that branch does not include the changes in this pull-request. The Jenkins build failed:

```
Executing: createrepo --update planex-build-root/RPMS
planex-install /repos/xen-api-backports /output/api-backports/PACKAGES.main
Traceback (most recent call last):
  File "/usr/bin/planex-install", line 64, in ?
    rpm_path = pkg_to_rpm[pkg_name]
KeyError: u'stunnel'
make[3]: *** [buildrpms] Error 1
make[2]: *** [__api-backports-build] Error 1
make[1]: *** [/local/bigdisc/jenkins-builds/jenkins-xen-api-backports-37/sanibel-bugfix/obj/.build-api-backports] Error 2
```

I'll set the test going again though, in case somehow it had not yet picked up the change of xenserver/planex#263

**Comment by thomassa** [comment]
@xen-git retest this please

**Comment by robhoes** [comment]
Tests have now passed, so I'll merge this.

**Pull request merged**
