### PR TITLE
HFX-1235: Copy <Update vhd-tool to 0.7.4> from Creedence to clearwater-sp1-lcm

### PR DESCRIPTION
**Pull request by Zhengchai**
Copy <Update vhd-tool to 0.7.4> from creedence (https://github.com/xenserver/xen-api-backports/pull/4) to clearwater-sp1-lcm for HFX-1235

### CODE REVIEW

**Comment by xen-git** [comment]
Can one of the admins verify this patch for testing?

**Comment by johnelse** [comment]
Build failure is due to jenkins running out disk space, not because of anything in the pull request.

**Comment by johnelse** [comment]
@xen-git test this please

**Comment by johnelse** [comment]
Looks good now; should probably go in at the same time as https://github.com/xapi-project/xen-api/pull/1852 once that's fixed up.

**Pull request merged**
